/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat1;

import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prado
 */
//la tabla es para el display del chat, asi queda nombre: mensaje
//extends es una herencia
public class GuestGUI extends javax.swing.JFrame {
    //al usar private finals se hace que no se pueda aplicar del todo herencia sobre las variables
    private final DefaultTableModel modelo;
    private final Client cliente;
    private final Server servidor;
    private String mensaje[];//el array es porque el mensaje viene en una lista que splitteo con el °

    /**
     * Creates new form GuestGUI
     */
    //se inicializa la gui y se crean el client y el sv
    public GuestGUI() {
        initComponents();
        modelo = (DefaultTableModel) tabla1.getModel();
        servidor = new Server(modelo, Integer.parseInt(puerto_Field.getText()));//agarra el puerto y lo convierte en integer(parseint)
        cliente = new Client(IP_Field.getText(), Integer.parseInt(puerto_Field.getText()));
    }
   
    //toma el mensaje recibido por el sv
    public void getMensaje(){
    mensaje = servidor.mensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        cuadro_de_texto = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        label_name = new java.awt.Label();
        label_ip = new java.awt.Label();
        label_port = new java.awt.Label();
        mensaje_field = new javax.swing.JTextField();
        nombre_field = new javax.swing.JTextField();
        puerto_Field = new javax.swing.JTextField();
        IP_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setActionCommand("send");
        button1.setBackground(new java.awt.Color(0, 204, 204));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 12)); // NOI18N
        button1.setLabel("Ok!");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 70, 40));

        tabla1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Mensaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla1.getTableHeader().setReorderingAllowed(false);
        cuadro_de_texto.setViewportView(tabla1);
        if (tabla1.getColumnModel().getColumnCount() > 0) {
            tabla1.getColumnModel().getColumn(0).setResizable(false);
            tabla1.getColumnModel().getColumn(0).setPreferredWidth(150);
            tabla1.getColumnModel().getColumn(1).setResizable(false);
            tabla1.getColumnModel().getColumn(1).setPreferredWidth(875);
        }

        getContentPane().add(cuadro_de_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1020, 520));

        label_name.setBackground(new java.awt.Color(255, 255, 255));
        label_name.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        label_name.setText("Nombre");
        getContentPane().add(label_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, -1));

        label_ip.setBackground(new java.awt.Color(255, 255, 255));
        label_ip.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        label_ip.setText("IP");
        getContentPane().add(label_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        label_port.setBackground(new java.awt.Color(255, 255, 255));
        label_port.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        label_port.setText("Puerto");
        getContentPane().add(label_port, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, -1));

        mensaje_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensaje_fieldActionPerformed(evt);
            }
        });
        mensaje_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mensaje_fieldKeyPressed(evt);
            }
        });
        getContentPane().add(mensaje_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 670, 40));

        nombre_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(nombre_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 200, 30));

        puerto_Field.setText("9000");
        getContentPane().add(puerto_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, 30));

        IP_Field.setText("127.0.0.1");
        getContentPane().add(IP_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//boton ok!
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try {
            servidor.Update(Integer.parseInt(puerto_Field.getText()));
            cliente.Update_Data(IP_Field.getText(), Integer.parseInt(puerto_Field.getText()));
            cliente.enviar_mensaje(nombre_field.getText(),mensaje_field.getText());
            modelo.addRow(new Object[]{nombre_field.getText(),mensaje_field.getText()});
            mensaje_field.setText(null);
        } catch (IOException ex) {
            System.out.println("no se llamó la función");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void nombre_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_fieldActionPerformed

    private void mensaje_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensaje_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensaje_fieldActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased
//enter key
    private void mensaje_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mensaje_fieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try {
            servidor.Update(Integer.parseInt(puerto_Field.getText()));
            cliente.Update_Data(IP_Field.getText(), Integer.parseInt(puerto_Field.getText()));
            cliente.enviar_mensaje(nombre_field.getText(),mensaje_field.getText());
            modelo.addRow(new Object[]{nombre_field.getText(),mensaje_field.getText()});
            mensaje_field.setText(null);
        } catch (IOException ex) {
            System.out.println("no se llamó la función");
            }
        }
    }//GEN-LAST:event_mensaje_fieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new GuestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IP_Field;
    private java.awt.Button button1;
    private javax.swing.JScrollPane cuadro_de_texto;
    private java.awt.Label label_ip;
    private java.awt.Label label_name;
    private java.awt.Label label_port;
    private javax.swing.JTextField mensaje_field;
    private javax.swing.JTextField nombre_field;
    private javax.swing.JTextField puerto_Field;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}